bucket_name: "labelstudiobackend-dev"
s3_model_path: "s3://sagemaker-us-east-1-100328509916/output_shapes_gen3_dillonchris_feb2025_batch8_1800_85epochs_2025-02-27-21-47-24/train/weights/best.pt"
model_path: "./model.pt"
class_model_path: ""
pdf_path: "s3://labelstudiobackend_dev/project5/TPG_Hotel_Indigo_Condensed_copy.pdf"
# pdf_path: "s3://beaverdiffgrambackend/test_company/project2/centrarudy_morningside_fullset.pdf"
model_version: "gen3"
threshold: 0.1
scale: 1.0
input_path: ""   # s3 input dir and the output dir
output_path: ""   # local output path under temp
tile_size: 640
task_name: "shape"
class_ids: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
p_class_ids: [0,1,2,3,4,6,7,8,10,11,12,13,14] # ['0', '1','2','3','4','6', '7', '8', '10', '11', '12', '13', '14']
thresholds: {'0':0.3,'1':0.25,'2':0.3,'3':0.2,'4':0.4,'5':0.4,'6':0.2}
format: 'label_studio'  # format option 
shape_detection: False
save_piece: False
device: '0'
temp_dir: "temp"
full_pic_ann: False
aws_access_key_id: ''
aws_secret_access_key: ''
region_name: us-east-1